default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  timeout: 10

development:
  <<: *default
  database: xpedia_dev
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: xpedia_test
  host: localhost
  port: 5432
  username: postgres
  password: postgres

production:
  <<: *default
  database: xpedia_prod
  host: localhost
  port: 5432
  username: postgres
  password: postgres